disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Sheffield Pinknic"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
# logo = "img/logo.png"
# secondaryLogo = "img/secondary-logo.png"
description = "Sheffield's Largest LGBTQ+ Event"
copyright = """
This website's content is released into the Public Domain under the Unlicense. 
Third-party materials are still subject to their respective licenses. 
See [https://pinknic.co.uk/license](/license) for more details and exceptions."""
